from pydantic import BaseModel, Field
from typing import Dict, Any

class ReportRequest(BaseModel):
    """
    Defines the shape of the incoming request body for generating a report.
    """
    farmer_name: str = Field(..., example="Amit Singh", description="The name of the farmer requesting the report.")
    lat: float = Field(..., example=28.6139, description="Latitude for the farm location.")
    lon: float = Field(..., example=77.2090, description="Longitude for the farm location.")
    crop_name: str = Field(..., example="Wheat", description="The name of the crop for the report.")

class ReportResponse(BaseModel):
    """
    Defines the shape of the final JSON response, including both weather data
    and the generated LLM report.
    """
    weather_data: Dict[str, Any] = Field(..., description="The raw JSON data received from the weather service.")
    llm_report: str = Field(..., description="The formatted, detailed crop report generated by the LLM.")

__all__=[
    "ReportRequest",
    "ReportResponse"
]